version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Arbor.App.Extensions
    versions:
    - 0.6.2
    - 0.7.0
  - dependency-name: Arbor.KVConfiguration.JsonConfiguration
    versions:
    - 1.2.0
  - dependency-name: Arbor.KVConfiguration.Urns
    versions:
    - 1.2.0
  - dependency-name: Arbor.KVConfiguration.Microsoft.Extensions.Configuration.Urns
    versions:
    - 1.2.0
  - dependency-name: Arbor.KVConfiguration.UserConfiguration
    versions:
    - 1.2.0
  - dependency-name: Arbor.KVConfiguration.DependencyInjection
    versions:
    - 1.2.0
  - dependency-name: Arbor.KVConfiguration.Core
    versions:
    - 1.2.0
  - dependency-name: Arbor.KVConfiguration.Schema.Json
    versions:
    - 1.2.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
    - 16.9.4
  - dependency-name: Serilog.AspNetCore
    versions:
    - 4.0.0
    - 4.1.0
  - dependency-name: Microsoft.Extensions.Diagnostics.HealthChecks
    versions:
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Hosting.WindowsServices
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Authentication.OpenIdConnect
    versions:
    - 5.0.2
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Mvc.NewtonsoftJson
    versions:
    - 5.0.4
  - dependency-name: Microsoft.CodeAnalysis.CSharp
    versions:
    - 3.9.0
  - dependency-name: Serilog.Sinks.Seq
    versions:
    - 5.0.0
